# Generated by Django 5.1.2 on 2024-10-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(default='Scheduled', max_length=50)),
            ],
        ),
    ]
